env:
  es2021: true
  node: true
  browser: true
parser: '@typescript-eslint/parser'
parserOptions:
  project: ./tsconfig.json
extends:
  - next
  - next/core-web-vitals
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - prettier
  - plugin:react/recommended
ignorePatterns:
  - '*.generated.ts'
  - graphql/types.ts
plugins:
  - react
  - '@typescript-eslint'
  - unused-imports
settings:
  react:
    version: detect
rules:
  react-hooks/exhaustive-deps: off
  react/jsx-uses-react: off
  react/react-in-jsx-scope: off
  '@next/next/no-img-element': off
  'react/prop-types': off
  sort-imports: 0
  'import/order':
    - warn
    - groups:
        - builtin
        - external
        - internal
      alphabetize:
        order: asc
  '@typescript-eslint/no-unused-vars': off
  '@typescript-eslint/no-empty-function': off
  unused-imports/no-unused-imports-ts: warn
