version: '3.9'
services:
  db:
    image: postgres:14.1
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  app:
    build: .
    command: /bin/sh -c "rm -f /app/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0' -e development"
    volumes:
      - .:/app
      - gem_data:/usr/local/bundle
    stdin_open: true
    tty: true
    ports:
      - '3000:3000'
    environment:
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - db
volumes:
  gem_data:
  db_data:
